### ISSUE TITLE
LEDs for 52840 dongle not working

### ISSUE THREAD

**Issue by mame82** [AprilBrother/ab-hardware#1]
The LED assignment for 52840 dongle isn't working at all.

Here's an excerpt of my board definitions, with respective comments on LEDs.

RED isn't working at all. Blue and green show weird behavior.

```
#ifndef APRBROTHER_DONGLE_H
#define APRBROTHER_DONGLE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "nrf_gpio.h"

// LED definitions for APRBROTHER dongle
// Each LED color is considered a separate LED
#define LEDS_NUMBER    4

#define LED1_G         NRF_GPIO_PIN_MAP(0,6)
#define LED2_R         NRF_GPIO_PIN_MAP(0,8)
#define LED2_G         NRF_GPIO_PIN_MAP(1,9)
#define LED2_B         NRF_GPIO_PIN_MAP(0,12)

#define LED_1          LED1_G
#define LED_2          LED2_R
#define LED_3          LED2_G
#define LED_4          LED2_B

#define LEDS_ACTIVE_STATE 0

#define LEDS_LIST { LED_1, LED_2, LED_3, LED_4 }

#define LEDS_INV_MASK  LEDS_MASK

// Totally messed, no RED at all
#define BSP_LED_0      LED_1 // blue, bright
#define BSP_LED_1      LED_2 // blue, barely noticeable
#define BSP_LED_2      LED_3 // green, only if LED_2 is on, too
#define BSP_LED_3      LED_4 // seems to toggle LED_2 somehow, without changing LED_4

// There is only one button for the application
#define BUTTONS_NUMBER 1

#define BUTTON_1       NRF_GPIO_PIN_MAP(1,6)
#define BUTTON_PULL    NRF_GPIO_PIN_PULLUP

#define BUTTONS_ACTIVE_STATE 0

#define BUTTONS_LIST { BUTTON_1 }

#define BSP_BUTTON_0   BUTTON_1

#define BSP_SELF_PINRESET_PIN NRF_GPIO_PIN_MAP(0,19)

#define HWFC           true

#ifdef __cplusplus
}
#endif

#endif // APRBROTHER_DONGLE_H
```

**Comment by mame82** [comment]
LOGITacker firmware for the dongle was added:
https://github.com/mame82/LOGITacker#24-april-brother-nrf52840-dongle

LED issues are referred here:
https://github.com/mame82/LOGITacker#241-remark-on-led-issues-of-aprbrother-dongle

**Comment by nieldk** [comment]
There is an interresting observation here. https://github.com/adafruit/circuitpython/issues/1174#issue-358262902

**Comment by mame82** [comment]
Behavior differs ... especially on BLUE LED ... not sure on undervoltage

```
#define BSP_LED_0      LED_1 // blue, bright
#define BSP_LED_1      LED_2 // blue, barely noticeable
#define BSP_LED_2      LED_3 // green, only if LED_2 is on, too
#define BSP_LED_3      LED_4 // seems to toggle LED_2 somehow, without changing LED_4
```

**Comment by volca** [comment]
@mame82 When did you buy the USB dongle?  We'll try to re-produce the issue with your code first

**Comment by volca** [comment]
I just tested one dongle with a test firmware. Please check  [the video](https://youtu.be/4mD8C8vB_KQ).

Here's the firmware file
[nrf52840.uf2.zip](https://github.com/AprilBrother/ab-hardware/files/3395166/nrf52840.uf2.zip)


Some early dongles are soldered with wrong RGB led so it has the issue.

**Comment by nieldk** [comment]
> I just tested one dongle with a test firmware. Please check [the video](https://youtu.be/4mD8C8vB_KQ).
> 
> Here's the firmware file
> [nrf52840.uf2.zip](https://github.com/AprilBrother/ab-hardware/files/3395166/nrf52840.uf2.zip)
> 
> Some early dongles are soldered with wrong RGB led so it has the issue.

Thanks @volca , but your video only show green blinking LED, and the blue LED. @mame82 mentioned that the issue is getting Red LED, and Green LED is only working together with Blue.

**Comment by volca** [comment]
The video shows blinking green --> blue -> red. Please check it again?

**Comment by mame82** [comment]
> > I just tested one dongle with a test firmware. Please check [the video](https://youtu.be/4mD8C8vB_KQ).
> > Here's the firmware file
> > [nrf52840.uf2.zip](https://github.com/AprilBrother/ab-hardware/files/3395166/nrf52840.uf2.zip)
> > Some early dongles are soldered with wrong RGB led so it has the issue.
> 
> Thanks @volca , but your video only show green blinking LED, and the blue LED. @mame82 mentioned that the issue is getting Red LED, and Green LED is only working together with Blue.

No, all 4 LEDs are shown (single color blue and RGB).

Unfortunately it still doesn't work out with my dongle, here's a video from the LED test firmware provided above [video](https://youtu.be/asLK6hE-gUA).

The dongles was have been ordered on May 16th (order #2169). Only 1 out of 3 arrived, still waiting for the others ... maybe it is a malfunction of the one which arrived.

Also, is there a way to disassemble the dongle, without destroying it. I noticed that you removed the upper side from the housing. On my version, the upper part of the housing is holding the USB-A plug together. Removing it would render the plug unusable.

**Comment by volca** [comment]
> The dongles was have been ordered on May 16th (order #2169). Only 1 out of 3 arrived, still waiting for the others

I can confirm the dongle was soldered wrong RGB LED. We've replaced all RGB LED for other dongles. Two dongles with new RGB LEDs were shipped out yesterday.

> Also, is there a way to disassemble the dongle, without destroying it. 

Unfortunately you must destroy the casing to disassemble the dongle (I also destroyed one casing today). But we can send some more new casings to you if you place another order for the dongle.

**Comment by nieldk** [comment]
OK, my bad, sorry guys. I also ordered new dongles (the ones I had are bricked), will be looking forward to test once they arrive.  @volca it seems my order 2310 is just about to ship, perhaps you can manage to add some housing to that ?

**Comment by mame82** [comment]
> I can confirm the dongle was soldered wrong RGB LED. We've replaced all RGB LED for other dongles. Two dongles with new RGB LEDs were shipped out yesterday.

So this means this issue does not exist, anymore! Nice. 

Btw. the external antenna performs really well, compared to the Nordic version with PCB antenna.

Looking forward to test the new dongles ... thanks for the support!

**Comment by volca** [comment]
@nieldk My colleague are making package for order #2310. She will add extra 3 empty housings and one more usb dongle to the package.

**Comment by nieldk** [comment]
> @nieldk My colleague are making package for order #2310. She will add extra 3 empty housings and one more usb dongle to the package.

Marvelous, thanks guys!
I will forward some to you @mame82 if you would like ?

**Comment by volca** [comment]
Thanks @mame82 and @nieldk for get the dongle compatible with the great software LOGITacker!

**Comment by mame82** [comment]
👍🍻

**Comment by volca** [comment]
closed. Reopen if need
