### ISSUE TITLE
Issue with April USB Dongle 52840

### ISSUE THREAD

**Issue by cHJlaXpoZXI** [AprilBrother/ab-hardware#2]
Hello,

I have an issue with my 52840 dongle. My dongle doesn’t seem to work. I’ve tested on Linux and Windows and nothing appear on USB debug. The dongle have a blue light but anything else.

I tried to flash Logitacker inside it and cannot have the USB storage for the firmware inside. I tried multiple time plug it with the button pushed or double push before plugin and nothing append.

Do you think my device is bricked?

Sorry for the inconvenience.
Thank you,

**Comment by volca** [comment]
Please try to use alcohol cotton ball to wash the copper in the USB port first. And insert the dongle to laptop again. It should make better touch for the USB port.

**Comment by cHJlaXpoZXI** [comment]
I've cleaned every port on 4 differents devices and the issue continue.

I think the dongle is dead or bad batch I don't know.

Thanks anyway.

**Comment by volca** [comment]
Where did you buy the dongle? Please contact the sales and they will send a replacement dongle to you

**Comment by cHJlaXpoZXI** [comment]
I bought my dongle in Aliexpress. Seller : BLE beacon Store

I will do it. Thanks for your help.

**Comment by volca** [comment]
It's our official store in Aliexpress. no problem. Please comment and refer the link in Aliexpress.

I closed the issue. Will re-open it if you have future problem
