### ISSUE TITLE
Setup/ programming instructions for abutton-v3

### ISSUE THREAD

**Issue by squix78** [AprilBrother/ab-hardware#3]
Hi
Where can I find setup instructions or programming instructions for abutton-v3

**Comment by volca** [comment]
We usually use our [ESP flasher](https://wiki.aprbrother.com/en/ESP_Flasher_Rev4.html) to program AButton V3. ESP flasher has 1.27mm pins which perfect match AButton V3.

**Comment by volca** [comment]
We'll write more instructions at [the wiki](https://wiki.aprbrother.com/en/AButton_V3.html#how-to-programming-your-own-firmware). closed the issue
