### ISSUE TITLE
nRF52840 dongle issue

### ISSUE THREAD

**Issue by unicornmafia** [AprilBrother/ab-hardware#4]
Hello, 

I bought two of your dongles, and I'm trying to figure out how to program them.  Is there some documentation on this?  I would like to connect these via usb to a linux machine and use them to scan nearby eddystone beacons, and then send the data back through the USB to the linux machine using a VSP.   Is this even possible with this dongle?  If so, can you give me a few pointers?

Thanks!

**Comment by volca** [comment]
The USB dongle nRF52840 is flashed with Adafruit nRF52 Bootloader and "BLE Peripheral Blink" from nRF5 SDK examples default. 

### How to put the dongle to bootloader mode

* Find a small hole on the case. Insert a needle into the hole press and hold on the button
* Plug the dongle to your laptop
* You will see a new thumb drive and a new serial port. It means the dongle work at bootloader mode

You can also check the introduce how to use the bootloader mode at [SparkFun's website](https://learn.sparkfun.com/tutorials/sparkfun-pro-nrf52840-mini-hookup-guide/all#using-the-bootloader). 

You can try to program [circuitpython firmware on the dongle](https://circuitpython.org/board/pca10059/)
